---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
  - name: task-repo
    path: go/src/github.com/pivotal-cf/cred-hub-acceptance-tests
  - name: subject-repo
    path: go/src/github.com/pivotal-cf/credhub-cli
run:
  path: go/src/github.com/pivotal-cf/cred-hub-acceptance-tests/ci/tasks/run-acceptance-tests/task.sh

params:
  API_URL:
